"""Manage saved augmentation configs under a directory, the same way
`core/exp_store.py` manages experiment directories under `experiments/`.

A saved config is a YAML file with an optional `meta:` block (creation date)
plus the `transforms:` list that `core/config.py::load_aug_file` already
knows how to read. The `meta:` block is additive — files without it
(hand-written, or generated by an older version of this CLI) still load fine.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

from cvbench.core.registry import Registry

AUGMENTATIONS_DIR = "workspace/augmentations"

AUG_REG = Registry(
    AUGMENTATIONS_DIR,
    not_found_label="Augmentation config",
    entity_name="augmentation config",
    param_hint="--augmentation",
    ext=".yaml",
)


def validate_aug_name(name: str) -> str:
    """Raise ValueError if name is not safe to use as a saved-config filename."""
    return AUG_REG.validate_name(name, what="Name")


def resolve_aug_file(name_or_path: str) -> str:
    """Resolve a saved config name or a path to an existing YAML file.

    Accepts a full/relative path, a bare saved name (AUGMENTATIONS_DIR/<name>.yaml),
    or a bare saved name that already includes the extension.
    """
    AUG_REG.base_dir = AUGMENTATIONS_DIR
    return AUG_REG.resolve(name_or_path)


def write_augmentation_text(name: str, content: str, directory: str | None = None) -> Path:
    """Write raw text (already-rendered YAML, comments and all) under NAME.

    Returns the path written to. Creates `directory` if it doesn't exist yet.
    """
    validate_aug_name(name)
    out_dir = Path(directory or AUGMENTATIONS_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{name}.yaml"
    with open(path, "w") as f:
        f.write(content)
    return path


def save_augmentation_config(
    name: str, transforms: list[dict], directory: str | None = None,
) -> Path:
    """Write TRANSFORMS (list of {"name", "prob", ...params} dicts) under NAME, uncommented.

    Returns the path written to. Creates `directory` if it doesn't exist yet.
    """
    doc = {
        "meta": {"created": date.today().isoformat()},
        "transforms": transforms,
    }
    content = yaml.dump(doc, default_flow_style=False, sort_keys=False)
    return write_augmentation_text(name, content, directory)


def list_saved_augmentations(directory: str | None = None) -> list[dict]:
    """Return [{"name", "path", "n_transforms", "modified"}, ...], newest first.

    Tolerates files with no `meta:` block (falls back to file mtime) and
    skips files that fail to parse as YAML.
    """
    d = Path(directory or AUGMENTATIONS_DIR)
    if not d.is_dir():
        return []

    entries = []
    for path in sorted(d.glob("*.yaml")):
        try:
            with open(path) as f:
                raw = yaml.safe_load(f) or {}
        except yaml.YAMLError:
            continue
        meta = raw.get("meta") or {}
        created = meta.get("created")
        if not created:
            created = date.fromtimestamp(path.stat().st_mtime).isoformat()
        entries.append({
            "name": path.stem,
            "path": str(path),
            "n_transforms": len(raw.get("transforms", []) or []),
            "modified": created,
        })

    entries.sort(key=lambda e: e["modified"], reverse=True)
    return entries
