"""Manage saved augmentation configs under a directory, the same way
`core/runs.py` manages experiment directories under `experiments/`.

A saved config is a YAML file with an optional `meta:` block (preset label,
creation date) plus the `transforms:` list that `core/config.py::load_aug_file`
already knows how to read. The `meta:` block is additive — files without it
(hand-written, or generated by an older version of this CLI) still load fine.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import click
import yaml

from cvbench.core._names import validate_slug

AUGMENTATIONS_DIR = "workspace/augmentations"


def validate_aug_name(name: str) -> str:
    """Raise ValueError if name is not safe to use as a saved-config filename."""
    return validate_slug(name, what="Name")


def resolve_aug_file(name_or_path: str) -> str:
    """Resolve a saved config name or a path to an existing YAML file.

    Accepts a full/relative path, a bare saved name (AUGMENTATIONS_DIR/<name>.yaml),
    or a bare saved name that already includes the extension.
    """
    p = Path(name_or_path)
    if p.is_file():
        return str(p)

    base = Path(AUGMENTATIONS_DIR) / name_or_path
    if base.is_file():
        return str(base)

    with_ext = base.with_suffix(".yaml")
    if with_ext.is_file():
        return str(with_ext)

    raise click.BadParameter(
        f"Augmentation config not found: '{name_or_path}' "
        f"(also tried '{with_ext}')",
        param_hint="--augmentation",
    )


def save_augmentation_config(
    name: str, transforms: list[dict], preset_label: str, directory: str | None = None,
) -> Path:
    """Write TRANSFORMS (list of {"name", "prob", ...params} dicts) under NAME.

    Returns the path written to. Creates `directory` if it doesn't exist yet.
    """
    validate_aug_name(name)
    out_dir = Path(directory or AUGMENTATIONS_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{name}.yaml"

    doc = {
        "meta": {"preset": preset_label, "created": date.today().isoformat()},
        "transforms": transforms,
    }
    with open(path, "w") as f:
        yaml.dump(doc, f, default_flow_style=False, sort_keys=False)
    return path


def list_saved_augmentations(directory: str | None = None) -> list[dict]:
    """Return [{"name", "path", "preset", "n_transforms", "modified"}, ...], newest first.

    Tolerates files with no `meta:` block (falls back to file mtime and a
    "custom" preset label) and skips files that fail to parse as YAML.
    """
    d = Path(directory or AUGMENTATIONS_DIR)
    if not d.is_dir():
        return []

    entries = []
    for path in sorted(d.glob("*.yaml")):
        try:
            with open(path) as f:
                raw = yaml.safe_load(f) or {}
        except yaml.YAMLError:
            continue
        meta = raw.get("meta") or {}
        created = meta.get("created")
        if not created:
            created = date.fromtimestamp(path.stat().st_mtime).isoformat()
        entries.append({
            "name": path.stem,
            "path": str(path),
            "preset": meta.get("preset", "custom"),
            "n_transforms": len(raw.get("transforms", []) or []),
            "modified": created,
        })

    entries.sort(key=lambda e: e["modified"], reverse=True)
    return entries
